apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/yourusername/python-app.git
    - name: revision
      value: main
---
apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
    - name: url
      value: docker.io/yourusername/python-app:latest
