apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: python-ci-cd-run
spec:
  pipelineRef:
    name: python-ci-cd-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: git-source
    - name: docker-image
      resourceRef:
        name: docker-image
